/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bishopofwales;

//import com.github.lalyos.jfiglet.FigletFont;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        
        Parent root = FXMLLoader.load(getClass().getResource("/primary.fxml"));
        primaryStage.setTitle("Synapse Project");
        primaryStage.setScene(new Scene(root, 600, 400));
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }
}
